name: telegram-webapp
services:
  telegram-bot-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: telegram_bot
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - telegram_bot_db_data:/var/lib/postgresql/data

  telegram-bot-app:
    image: hakankaan/telegram-bot:latest
    build:
      context: .
      dockerfile: ./apps/telegram-bot/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - telegram-bot-db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_API_URL=${TELEGRAM_API_URL}
      - WEB_APP_URL=${WEB_APP_URL}

  telegram-bot-migrations:
    image: hakankaan/telegram-bot:latest
    build:
      context: .
      dockerfile: ./apps/telegram-bot/Dockerfile
      target: builder
    depends_on:
      - telegram-bot-db
    environment:
      - DATABASE_URL=${DATABASE_URL}
    entrypoint: ["npx", "drizzle-kit", "migrate"]

  
  web-app:
    image: hakankaan/web-app:latest
    build:
      context: .
      dockerfile: ./apps/web-app/Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production


volumes:
  telegram_bot_db_data:
